version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-net
    depends_on:
      - password-generator
      - service_one
      - service_two


  password-generator:
    image: madbox098/password-generator
    networks:
      - microservices-net
    deploy:
      replicas: 1

  
  service_one:
    image: madbox098/service-one
    networks:
      - microservices-net
   
    deploy:
      replicas: 1

  service_two:
    image: madbox098/service-two
    networks:
      - microservices-net
  
    deploy:
      replicas: 1


networks:
  microservices-net:
    driver: overlay
