events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://password-generator:5000;
        }

        location /service1 {
            proxy_pass http://service_one:5000;
        }

        location /service2 {
            proxy_pass http://service_two:5000;
        }
    }
}
